package unicam.spm2023.selenium;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.*;


public class FirstSeleniumBrowserTest {
  private static WebDriver driver;
  private static Map<String, Object> vars;
  static JavascriptExecutor js;
  static ChromeOptions options = new ChromeOptions();

  @BeforeEach
  public void setUp() {
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterAll
  public static void tearDown() {
    driver.quit();
  }

  @Test
  public void firstSeleniumBrowserTest() {
    driver.get("https://pros.unicam.it/");
    driver.manage().window().setSize(new Dimension(1267, 665));
    driver.findElement(By.id("svg-search")).click();
    driver.findElement(By.name("s")).sendKeys("Digital twin");
    driver.findElement(By.name("s")).sendKeys(Keys.ENTER);
  }
}
